
# 项目数据库地址
# project_DB:
#   host: 172.25.1.14
#   port: 3306
#   dbname: fpsyyzwcm_sdjdbc1
#   username: root
#   password: zrsf2012
  
# 项目工程ip和端口地址
hp: http://172.25.2.106:52158
    

# 其他配置
other_data:
    appid: b292a318343e62bbd3fb97c66344a6300dae158de43eba8e24d126b12ce09d64
    aeskey: 0A15027A838704C3
    
    
save_path:
    test_case_path: test_case/test_case.xlsx
    dp: data_file/dp
    expected: data_file/expected
    req_data: data_file/req_data/data
    req_globle: data_file/req_data/globle
    req_params: data_file/req_data/params
    output: data_file/output

