
# 项目数据库地址
project_DB:
  host: 172.25.1.14
  port: 3306
  dbname: fpsyyzwcm_sdjdbc1
  username: root
  password: zrsf2012
  
# 项目工程ip和端口地址
engineering_hp:
    fpsyy-interface: http://172.25.2.91:59133
    

# 其他配置
other_data:
    aesKey: ABCD123dJKHger34
    
    
save_path:
    test_case_path: zdyt_mysql/test_case/test_case.xlsx
    test_data_path: zdyt_mysql/data_file/
    
    
    
    
    
    






